version: '3.8'
services:
  tsubaki:
    container_name: tsubaki
    restart: always
    build: ./app
    depends_on:
      - postgresql
      - prometheus
      - redis
    volumes:
      - /run/media/noel/Storage/Projects/Arisu/Arisu/app/config.yml:/app/arisu/tsubaki/build/config.yml:ro
      # - arisu_project_data:/var/lib/arisu/projects:rw

  zookeeper:
    image: bitnami/zookeeper:3.7
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-cluster

  kafka1:
    image: bitnami/kafka:2.8.1
    container_name: kafka-1
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - kafka-cluster

  kafka2:
    image: bitnami/kafka:2.8.1
    container_name: kafka-2
    ports:
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2:9093,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - kafka-cluster

  kafka3:
    image: bitnami/kafka:2.8.1
    container_name: kafka-3
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka3:9094,EXTERNAL://localhost:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - kafka-cluster

  postgresql:
    container_name: postgres
    restart: always
    image: postgres:latest
    ports:
      - '5432:5432'
    networks:
      - arisu
    volumes:
      - arisu_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-arisu}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-arisu}
      POSTGRES_DB: ${DATABASE_NAME:-arisu}

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - arisu
    volumes:
      - arisu_redis:/data

  prometheus:
    container_name: prometheus
    build: ./docker/prometheus
    restart: always
    networks:
      - default

networks:
  arisu:
    internal: true
    name: arisu
    driver: bridge

  kafka-cluster:
    name: kafka-cluster
    driver: bridge

volumes:
  #arisu_projects_cache:
  arisu_postgres:
  arisu_redis:
