version: '3.8'
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached

  redis:
    image: redis:latest
    restart: unless-stopped
    network_mode: service:workspace
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    restart: unless-stopped
    network_mode: service:workspace
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: bitnami/zookeeper:latest
    restart: always
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_ID: 1
      ZOOKEEPER_SERVER_ID: zookeeper
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  kafka:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - '9092:9092'
      - '29092:29092'
    volumes:
      - kafka-data:/var/lib/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITAL_REBALANCE_DELAY_MS: 0
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092

volumes:
  postgres_data:
  redis_data:
  kafka_data:
