#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$PWD/bin/liblog.sh"

info "Linting projects..."
yarn workspaces foreach --from '{@arisu/tsubaki,@arisu/github}' -p -R run lint:ci

info "Checking if we can compile"
yarn workspaces foreach --from '{@arisu/tsubaki,@arisu/github}' -p -R run build:ci

info "✔ Everything has been checked. :3"
