name: ESLint
on:
  push:
    branches:
      - 'feature/**'
      - 'issue/gh-**'
      - master
      - staging

    paths-ignore:
      - '.github/**'
      - '.husky/**'
      - '.vscode/**'
      - 'assets/**'
      - 'locales/**'
      - 'docker/**'
      - '.kube/**'
      - '.idea/**'
      - '.dockerignore'
      - '.eslintignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'
      - '.prettierc.json'
      - '.prettierignore'

  pull_request:
    branches:
      - 'feature/**'
      - 'issue/gh-**'
      - 'bug/gh-**'
      - staging
      - master

    paths-ignore:
      - '.github/**'
      - '.husky/**'
      - '.vscode/**'
      - 'assets/**'
      - 'locales/**'
      - 'docker/**'
      - '.kube/**'
      - '.idea/**'
      - '.dockerignore'
      - '.eslintignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'
      - '.prettierc.json'
      - '.prettierignore'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: arisu
          POSTGRES_PASSWORD: owowhatsthis
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

        ports:
          - '5432:5432'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installs all global packages
        run: npm i -g eslint typescript

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-

      - name: Installs local packages
        run: yarn

      - name: Generate Prisma schema
        working-directory: ${{ github.workspace }}/app
        run: yarn generate

      - name: Lints the repository and checks for linting errors
        run: yarn lint

      - name: Compiles the project to check for any build errors
        run: yarn build
