name: Push to Production
on:
  push:
    branches:
      - master

    paths-ignore:
      - '.github/**'
      - '.husky/**'
      - '.vscode/**'
      - 'assets/**'
      - 'locales/**'
      - 'docker/**'
      - '.kube/**'
      - '.idea/**'
      - '.dockerignore'
      - '.eslintignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'
      - '.prettierc.json'
      - '.prettierignore'

jobs:
  push-prod:
    name: Push to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login into floof registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login registry.floofy.dev -u august --password-stdin

      # - name: Build container (arisuland/tsubaki)
      # - working-directory: ./app
      # - run: docker build . -t arisuland/tsubaki:latest

      # - name: Build container (arisuland/arisu)
      # - working-directory: ./web
      # - run: docker build . -t arisuland/arisu:latest

      - name: Build container (arisu/gh-to-youtrack)
        working-directory: ./gh-to-youtrack
        run: docker build . -t registry.floofy.dev/arisu/gh-to-youtrack:${{github.sha}}

      - name: Push to registry
        run: docker push registry.floofy.dev/arisu/gh-to-youtrack:${{github.sha}}

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: push-prod
    steps:
      - name: Login to Kubernetes
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Set tag
        run: kubectl set image deployment/gh-to-youtrack gh-to-youtrack=registry.floofy.dev/arisu/gh-to-youtrack:${{github.sha}} --namespace arisu

      - name: Deploy to Kubernetes :3
        run: kubectl rollout status deployment/gh-to-youtrack --namespace arisu
